package MazeApp;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;

public class GeneratorTest {
//    @Test
//    void generateFunctional() {
//        Maze maze;
//        maze = new Maze(100, 100, 10, false, "Arrows", "TITLE", "AUTHOR", null, null, null, null);
//        Maze.CellState[][] mock;
//        mock = [[EXTERNALWALL, EXTERNALWALL, EXTERNALWALL, EXTERNALWALL, EXTERNALWALL, EXTERNALWALL, EXTERNALWALL, EXTERNALWALL, EXTERNALWALL], [EXTERNALWALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EXTERNALWALL], [EXTERNALWALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EXTERNALWALL], [EXTERNALWALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EXTERNALWALL], [EXTERNALWALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EXTERNALWALL], [EXTERNALWALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EXTERNALWALL], [EXTERNALWALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EXTERNALWALL], [EXTERNALWALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EXTERNALWALL], [EXTERNALWALL, EXTERNALWALL, EXTERNALWALL, EXTERNALWALL, EXTERNALWALL, EXTERNALWALL, EXTERNALWALL, EXTERNALWALL, EXTERNALWALL]];
//        assertArrayEquals(mock, new Generator(maze).generate());
//    }
}